export { default as Home } from './Home'
export { default as Collections } from './Collections'
export { default as CollectionPhotos } from './CollectionPhotos'
export { default as SearchFeed } from './SearchFeed'
export { default as ImageFeed } from './ImageFeed'
export { default as ErrorPage } from './ErrorPage'
export { default as SuccessAuth } from './SuccessAuth'